public enum OpCode {
    CONST_INT,
    CONST_LONG,
    CONST_DOUBLE,
    CONST_BIGINT,
    CONST_STR,
    CONST_BOOL,
    CONST_NIL,
    CONST_FUNC,
    CALL_VALUE,
    RETURN,
    ARRAY_NEW,
    ARRAY_GET,
    ARRAY_SET,
    ADD, SUB, MUL, DIV,
    NOT,
    EQ, NEQ,
    LT, GT, LE, GE,
    LOAD, STORE,
    IMPORT, CALL,
    PRINT, POP,
    JUMP,
    JUMP_IF_FALSE
}